name: flow_ui_datatable_example
description: Example app for flow_ui_datatable package.
publish_to: 'none'

environment:
  sdk: ^3.12.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flow_ui_datatable:
    path: ../
  lucide_icons_flutter: ^3.0.0
  highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
